spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    #    sqlScriptEncoding: UTF-8
    #    url: jdbc:h2:mem:testdb
    #    initialization-mode: always
    url: jdbc:postgresql://ec2-54-246-90-10.eu-west-1.compute.amazonaws.com:5432/d63ioiv9bi9o1n
    driverClassName: org.postgresql.Driver
    username: udywhccahycjia
    password: 36a8f5965c323599d2171471d908ff3c36e2aa56bb8752c52522ed0ff98f4c0a
    initialization-mode: always
